CREATE TABLE loai_bao_cao (
	Loai_ID INT IDENTITY (1,1) PRIMARY KEY,
	ten_loai VARCHAR(255) NOT NULL,
	ma_loai VARCHAR(255) NOT NULL,
);

CREATE TABLE bo_phan(
	BP_ID INT IDENTITY (1,1) PRIMARY KEY,
	Phong_bo_phan VARCHAR(255) NOT NULL,
);

CREATE TABLE nhan_vien(
	NV_ID INT IDENTITY (1,1) PRIMARY KEY,
	Ten VARCHAR(255) NOT NULL,
	Ngay_sinh DATE NOT NULL,
	Chuc_vu VARCHAR(255) NOT NULL,
	Gioi_tinh VARCHAR (255) NOT NULL,
	BP_ID INT NOT NULL FOREIGN KEY REFERENCES bo_phan(BP_ID),
);

CREATE TABLE bao_cao(
	BC_ID  INT IDENTITY (1,1) PRIMARY KEY,
	Ten_bao_cao VARCHAR(255) NOT NULL,
	Ma_so_bao_cao VARCHAR(255) NOT NULL,
	NV_ID INT NOT NULL  FOREIGN KEY REFERENCES nhan_vien(NV_ID),
	Loai_ID INT NOT NULL  FOREIGN KEY REFERENCES loai_bao_cao(Loai_ID),
);

CREATE TABLE nhanvien_baocao(
		BP_ID INT NOT NULL FOREIGN KEY REFERENCES bo_phan(BP_ID),
		BC_ID INT NOT NULL FOREIGN KEY REFERENCES  bao_cao(BC_ID),
);

